language: ruby
cache: bundler
rvm:
- 2.3.2
services:
  - docker
deploy:
  skip_cleanup: true
  edge: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Operating Systems & Virtualization
  client_key: ".travis/client.pem"
  on:
    tags: true
env:
  global:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
before_deploy:
- openssl aes-256-cbc -K $encrypted_95553ca09dad_key -iv $encrypted_95553ca09dad_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
